application: vitacademicsdev
version: 5
runtime: python27
api_version: 1
threadsafe: yes


inbound_services:
- warmup
- mail

handlers:
- url: .*
  script: helloworld.app

libraries:
- name: webapp2
  version: "2.5.2"
